//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFV_FOTO_PRODUTO
    {
        public string CodMarca { get; set; }
        public string CodProdutoFoto { get; set; }
        public byte[] Imagem { get; set; }
        public string CtrlOperacao { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
        public decimal ID { get; set; }
        public Nullable<decimal> IDExterno { get; set; }
    }
}
