//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFV_TABELA_SINCRONIZACAO_TBT
    {
        public AFV_TABELA_SINCRONIZACAO_TBT()
        {
            this.AFV_CAMPOS_SINCRONIZACAO_TBT = new HashSet<AFV_CAMPOS_SINCRONIZACAO_TBT>();
        }
    
        public string NomeTabela { get; set; }
        public string TipoSincronizacao { get; set; }
        public string Alias { get; set; }
        public decimal IndGenerica { get; set; }
        public Nullable<decimal> Ordem { get; set; }
        public decimal IndBackup { get; set; }
        public decimal IndDelete { get; set; }
        public string TipoAcaoTabela { get; set; }
        public Nullable<System.DateTime> UltimaAtualizacao { get; set; }
        public Nullable<int> MaxRegister { get; set; }
        public string TipoCargaERP { get; set; }
        public string Dispositivo { get; set; }
        public string NomeTabelaCliente { get; set; }
        public string ComandoConsulta { get; set; }
        public string ComandoConsultaCount { get; set; }
        public string ComandoExportacaoCliente { get; set; }
        public string ComandoSincronizacao { get; set; }
        public string ComandoAtualizacao { get; set; }
        public string ComandoControleFluxo { get; set; }
        public int Essencial { get; set; }
    
        public virtual ICollection<AFV_CAMPOS_SINCRONIZACAO_TBT> AFV_CAMPOS_SINCRONIZACAO_TBT { get; set; }
    }
}
