//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFV_LOG_ERRO_CARGA
    {
        public string Tabela { get; set; }
        public System.DateTime DataErro { get; set; }
        public string Mensagem { get; set; }
        public string Comando { get; set; }
    }
}
