//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFV_INSTALACAO
    {
        public int CodInstalacao { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public string NomeMaquina { get; set; }
        public string Ip { get; set; }
        public string Login { get; set; }
        public string Dispositivo { get; set; }
    }
}
