//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AFV_CAMPOS_SINCRONIZACAO_TBT
    {
        public string NOMETABELA { get; set; }
        public string ORIGEM { get; set; }
        public string DESTINO { get; set; }
    
        public virtual AFV_TABELA_SINCRONIZACAO_TBT AFV_TABELA_SINCRONIZACAO_TBT { get; set; }
    }
}
