//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_GRADE_ITEM_PEDIDO
    {
        public string CodPedido { get; set; }
        public string CodItemPedido { get; set; }
        public string CodGradeItemPedido { get; set; }
        public string CodDerivacao { get; set; }
        public decimal Qtd { get; set; }
        public Nullable<decimal> QtdFaturada { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual TBT_DERIVACAO TBT_DERIVACAO { get; set; }
        public virtual TBT_ITEM_PEDIDO TBT_ITEM_PEDIDO { get; set; }
    }
}
