//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_CARTEIRA_CLIENTE
    {
        public string CodPessoa { get; set; }
        public string CodPessoaCliente { get; set; }
        public int IndPrincipal { get; set; }
        public Nullable<decimal> Comissao { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual TBT_PESSOA_CLIENTE TBT_PESSOA_CLIENTE { get; set; }
        public virtual TBT_PESSOA TBT_PESSOA { get; set; }
    }
}
