//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_GRADE_MODELO
    {
        public string CodGrade { get; set; }
        public string CodMarca { get; set; }
        public string CodLinha { get; set; }
        public string CodModelo { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
        public string CodProporcionalidade { get; set; }
    
        public virtual TBT_GRADE TBT_GRADE { get; set; }
        public virtual TBT_MODELO TBT_MODELO { get; set; }
    }
}
