//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_GRUPO_CLIENTE
    {
        public TBT_GRUPO_CLIENTE()
        {
            this.TBT_PESSOA_CLIENTE = new HashSet<TBT_PESSOA_CLIENTE>();
        }
    
        public string CodGrupoCliente { get; set; }
        public string Descricao { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual ICollection<TBT_PESSOA_CLIENTE> TBT_PESSOA_CLIENTE { get; set; }
    }
}
