//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_TABELA_PRECO
    {
        public TBT_TABELA_PRECO()
        {
            this.TBT_CARRINHO = new HashSet<TBT_CARRINHO>();
            this.TBT_MODELO_TABELA_PRECO = new HashSet<TBT_MODELO_TABELA_PRECO>();
            this.TBT_MODELO_TABELA_PRECO1 = new HashSet<TBT_MODELO_TABELA_PRECO>();
            this.TBT_PEDIDO = new HashSet<TBT_PEDIDO>();
            this.TBT_PESSOA = new HashSet<TBT_PESSOA>();
        }
    
        public string CodTabelaPreco { get; set; }
        public string Moeda { get; set; }
        public string Descricao { get; set; }
        public Nullable<System.DateTime> DataInicioVigencia { get; set; }
        public Nullable<System.DateTime> DataFinalVigencia { get; set; }
        public Nullable<decimal> Tipo { get; set; }
        public decimal IndAtivo { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual ICollection<TBT_CARRINHO> TBT_CARRINHO { get; set; }
        public virtual ICollection<TBT_MODELO_TABELA_PRECO> TBT_MODELO_TABELA_PRECO { get; set; }
        public virtual ICollection<TBT_MODELO_TABELA_PRECO> TBT_MODELO_TABELA_PRECO1 { get; set; }
        public virtual ICollection<TBT_PEDIDO> TBT_PEDIDO { get; set; }
        public virtual ICollection<TBT_PESSOA> TBT_PESSOA { get; set; }
    }
}
