//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_ITEM_PEDIDO
    {
        public TBT_ITEM_PEDIDO()
        {
            this.TBT_GRADE_ITEM_PEDIDO = new HashSet<TBT_GRADE_ITEM_PEDIDO>();
        }
    
        public string CodPedido { get; set; }
        public string CodItemPedido { get; set; }
        public string CodProduto { get; set; }
        public string CodGrade { get; set; }
        public Nullable<System.DateTime> DataEntrega { get; set; }
        public Nullable<decimal> QtdCaixa { get; set; }
        public Nullable<decimal> QtdTotal { get; set; }
        public Nullable<decimal> QtdFaturada { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<decimal> ValorUnitarioLiquido { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public string CodEmpresa { get; set; }
        public string CodFilial { get; set; }
        public string SerieNF { get; set; }
        public string NumeroNF { get; set; }
        public Nullable<decimal> PercentualDesconto { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual TBT_GRADE TBT_GRADE { get; set; }
        public virtual ICollection<TBT_GRADE_ITEM_PEDIDO> TBT_GRADE_ITEM_PEDIDO { get; set; }
        public virtual TBT_PEDIDO TBT_PEDIDO { get; set; }
        public virtual TBT_PRODUTO TBT_PRODUTO { get; set; }
    }
}
