//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_ITEM_CARRINHO
    {
        public TBT_ITEM_CARRINHO()
        {
            this.TBT_GRADE_ITEM_CARRINHO = new HashSet<TBT_GRADE_ITEM_CARRINHO>();
        }
    
        public string CodCarrinho { get; set; }
        public decimal CodItemCarrinho { get; set; }
        public string CodProduto { get; set; }
        public string CodGrade { get; set; }
        public Nullable<System.DateTime> DataEntrega { get; set; }
        public Nullable<decimal> QtdCaixa { get; set; }
        public Nullable<decimal> QtdTotal { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<decimal> ValorUnitarioLiquido { get; set; }
        public Nullable<decimal> PercDesc { get; set; }
        public Nullable<decimal> CodInstalacao { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
        public decimal ID { get; set; }
    
        public virtual TBT_CARRINHO TBT_CARRINHO { get; set; }
        public virtual TBT_GRADE TBT_GRADE { get; set; }
        public virtual ICollection<TBT_GRADE_ITEM_CARRINHO> TBT_GRADE_ITEM_CARRINHO { get; set; }
        public virtual TBT_PRODUTO TBT_PRODUTO { get; set; }
    }
}
