//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_DERIVACAO
    {
        public TBT_DERIVACAO()
        {
            this.TBT_DERIVACAO_GRADE = new HashSet<TBT_DERIVACAO_GRADE>();
            this.TBT_GRADE_ITEM_CARRINHO = new HashSet<TBT_GRADE_ITEM_CARRINHO>();
            this.TBT_GRADE_ITEM_PEDIDO = new HashSet<TBT_GRADE_ITEM_PEDIDO>();
            this.TBT_ITEM_PRONTA_ENTREGA = new HashSet<TBT_ITEM_PRONTA_ENTREGA>();
            this.TBT_PRODUTO_TAMANHO = new HashSet<TBT_PRODUTO_TAMANHO>();
        }
    
        public string CodDerivacao { get; set; }
        public string Descricao { get; set; }
        public Nullable<int> CodSubGrade { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual ICollection<TBT_DERIVACAO_GRADE> TBT_DERIVACAO_GRADE { get; set; }
        public virtual ICollection<TBT_GRADE_ITEM_CARRINHO> TBT_GRADE_ITEM_CARRINHO { get; set; }
        public virtual ICollection<TBT_GRADE_ITEM_PEDIDO> TBT_GRADE_ITEM_PEDIDO { get; set; }
        public virtual ICollection<TBT_ITEM_PRONTA_ENTREGA> TBT_ITEM_PRONTA_ENTREGA { get; set; }
        public virtual ICollection<TBT_PRODUTO_TAMANHO> TBT_PRODUTO_TAMANHO { get; set; }
    }
}
