//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_PESSOA_MARCA
    {
        public string CodPessoa { get; set; }
        public string CodMarca { get; set; }
        public string TipoAcesso { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual TBT_MARCA TBT_MARCA { get; set; }
        public virtual TBT_PESSOA TBT_PESSOA { get; set; }
    }
}
