//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_ITEM_PRONTA_ENTREGA
    {
        public string CodItemProntaEntrega { get; set; }
        public string CodProduto { get; set; }
        public string CodDerivacao { get; set; }
        public string CodGrade { get; set; }
        public Nullable<decimal> QtdCaixa { get; set; }
        public Nullable<decimal> Quantidade { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual TBT_DERIVACAO TBT_DERIVACAO { get; set; }
        public virtual TBT_GRADE TBT_GRADE { get; set; }
        public virtual TBT_PRODUTO TBT_PRODUTO { get; set; }
    }
}
