//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_TITULO
    {
        public string CodEmpresa { get; set; }
        public string CodFilial { get; set; }
        public string NumeroTitulo { get; set; }
        public string CodPessoaCliente { get; set; }
        public string CodSituacaoTitulo { get; set; }
        public Nullable<int> NumeroTituloBanco { get; set; }
        public string Tipo { get; set; }
        public string CodPortador { get; set; }
        public Nullable<System.DateTime> DataVencimento { get; set; }
        public Nullable<System.DateTime> DataPagamento { get; set; }
        public Nullable<decimal> ValorAberto { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<int> ValorPago { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public string CodFilialNF { get; set; }
        public string NumeroNF { get; set; }
        public string SerieNF { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual TBT_PESSOA_CLIENTE TBT_PESSOA_CLIENTE { get; set; }
        public virtual TBT_PORTADOR TBT_PORTADOR { get; set; }
        public virtual TBT_SITUACAO_TITULO TBT_SITUACAO_TITULO { get; set; }
    }
}
