//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_PRODUTO
    {
        public TBT_PRODUTO()
        {
            this.TBT_ITEM_CARRINHO = new HashSet<TBT_ITEM_CARRINHO>();
            this.TBT_ITEM_PEDIDO = new HashSet<TBT_ITEM_PEDIDO>();
            this.TBT_ITEM_PRONTA_ENTREGA = new HashSet<TBT_ITEM_PRONTA_ENTREGA>();
            this.TBT_PRODUTO_RELACIONADO = new HashSet<TBT_PRODUTO_RELACIONADO>();
            this.TBT_PRODUTO_RELACIONADO1 = new HashSet<TBT_PRODUTO_RELACIONADO>();
            this.TBT_PRODUTO_TAMANHO = new HashSet<TBT_PRODUTO_TAMANHO>();
        }
    
        public string CodProduto { get; set; }
        public string CodMarca { get; set; }
        public string CodLinha { get; set; }
        public string CodModelo { get; set; }
        public string Descricao { get; set; }
        public string DescricaoCompleta { get; set; }
        public string DescricaoMaterial { get; set; }
        public string DescricaoCor { get; set; }
        public string CodBarra { get; set; }
        public Nullable<int> Ranking { get; set; }
        public Nullable<decimal> PrecoVenda { get; set; }
        public string CodNivel1 { get; set; }
        public string CodNivel2 { get; set; }
        public string CodGrupoProduto { get; set; }
        public string CodColecao { get; set; }
        public string CodCor { get; set; }
        public string CodProdutoFoto { get; set; }
        public int IndProntaEntrega { get; set; }
        public int VendaBloqueada { get; set; }
        public string DataFinalNovidade { get; set; }
        public int IndMidia { get; set; }
        public string Situacao { get; set; }
        public string Dimensoes { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual TBT_COLECAO TBT_COLECAO { get; set; }
        public virtual TBT_COR TBT_COR { get; set; }
        public virtual TBT_GRUPO_PRODUTO TBT_GRUPO_PRODUTO { get; set; }
        public virtual ICollection<TBT_ITEM_CARRINHO> TBT_ITEM_CARRINHO { get; set; }
        public virtual ICollection<TBT_ITEM_PEDIDO> TBT_ITEM_PEDIDO { get; set; }
        public virtual ICollection<TBT_ITEM_PRONTA_ENTREGA> TBT_ITEM_PRONTA_ENTREGA { get; set; }
        public virtual TBT_MODELO TBT_MODELO { get; set; }
        public virtual TBT_NIVEL1 TBT_NIVEL1 { get; set; }
        public virtual TBT_NIVEL2 TBT_NIVEL2 { get; set; }
        public virtual ICollection<TBT_PRODUTO_RELACIONADO> TBT_PRODUTO_RELACIONADO { get; set; }
        public virtual ICollection<TBT_PRODUTO_RELACIONADO> TBT_PRODUTO_RELACIONADO1 { get; set; }
        public virtual ICollection<TBT_PRODUTO_TAMANHO> TBT_PRODUTO_TAMANHO { get; set; }
    }
}
