//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_MODELO_TABELA_PRECO
    {
        public string CodTabelaPreco { get; set; }
        public string CodMarca { get; set; }
        public string CodLinha { get; set; }
        public string CodModelo { get; set; }
        public decimal Preco { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual TBT_MODELO TBT_MODELO { get; set; }
        public virtual TBT_MODELO TBT_MODELO1 { get; set; }
        public virtual TBT_TABELA_PRECO TBT_TABELA_PRECO { get; set; }
        public virtual TBT_TABELA_PRECO TBT_TABELA_PRECO1 { get; set; }
    }
}
