//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_CARRINHO
    {
        public TBT_CARRINHO()
        {
            this.TBT_CRITICA_CARRINHO = new HashSet<TBT_CRITICA_CARRINHO>();
            this.TBT_ITEM_CARRINHO = new HashSet<TBT_ITEM_CARRINHO>();
        }
    
        public string CodCarrinho { get; set; }
        public string CodPedido { get; set; }
        public string CodMarca { get; set; }
        public string CodPessoaCliente { get; set; }
        public string CodPessoaRepresentante { get; set; }
        public string CodPessoaPreposto { get; set; }
        public string CodSituacaoPedido { get; set; }
        public string CodTipoPedido { get; set; }
        public Nullable<decimal> CodUsuario { get; set; }
        public string CodTabelaPreco { get; set; }
        public string CodCondicaoPagamento { get; set; }
        public string CodColecao { get; set; }
        public string CodAtendimento { get; set; }
        public Nullable<System.DateTime> DataEmissao { get; set; }
        public Nullable<System.DateTime> DataEntrega { get; set; }
        public Nullable<int> QtdTotal { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
        public Nullable<decimal> ValorTotalLiquido { get; set; }
        public string OrdemCompra { get; set; }
        public string Observacoes { get; set; }
        public Nullable<decimal> PercentualDesconto { get; set; }
        public Nullable<decimal> PercentualComissaoRep { get; set; }
        public string CifFob { get; set; }
        public string Email { get; set; }
        public string CodFilial { get; set; }
        public string CodTransportadora { get; set; }
        public string CodRedespacho { get; set; }
        public string CodPedidoOrigem { get; set; }
        public Nullable<decimal> CodInstalacao { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
        public decimal ID { get; set; }
    
        public virtual ICollection<TBT_CRITICA_CARRINHO> TBT_CRITICA_CARRINHO { get; set; }
        public virtual ICollection<TBT_ITEM_CARRINHO> TBT_ITEM_CARRINHO { get; set; }
        public virtual TBT_COLECAO TBT_COLECAO { get; set; }
        public virtual TBT_CONDICAO_PAGAMENTO TBT_CONDICAO_PAGAMENTO { get; set; }
        public virtual TBT_MARCA TBT_MARCA { get; set; }
        public virtual TBT_PESSOA_CLIENTE TBT_PESSOA_CLIENTE { get; set; }
        public virtual TBT_PESSOA TBT_PESSOA { get; set; }
        public virtual TBT_PESSOA TBT_PESSOA1 { get; set; }
        public virtual TBT_SITUACAO_PEDIDO TBT_SITUACAO_PEDIDO { get; set; }
        public virtual TBT_TABELA_PRECO TBT_TABELA_PRECO { get; set; }
        public virtual TBT_TIPO_PEDIDO TBT_TIPO_PEDIDO { get; set; }
        public virtual TBT_USUARIO TBT_USUARIO { get; set; }
    }
}
