//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_PESSOA_CLIENTE
    {
        public TBT_PESSOA_CLIENTE()
        {
            this.TBT_CARRINHO = new HashSet<TBT_CARRINHO>();
            this.TBT_CARTEIRA_CLIENTE = new HashSet<TBT_CARTEIRA_CLIENTE>();
            this.TBT_ENDERECO_CLIENTE = new HashSet<TBT_ENDERECO_CLIENTE>();
            this.TBT_NOTA_FISCAL = new HashSet<TBT_NOTA_FISCAL>();
            this.TBT_PEDIDO = new HashSet<TBT_PEDIDO>();
            this.TBT_TITULO = new HashSet<TBT_TITULO>();
        }
    
        public string CodPessoaCliente { get; set; }
        public string RazaoSocial { get; set; }
        public string NomeFantasia { get; set; }
        public string CNPJ { get; set; }
        public string CodGrupoCliente { get; set; }
        public string CodSituacaoCliente { get; set; }
        public string CodCategoriaCliente { get; set; }
        public string Email { get; set; }
        public string EmailNFE { get; set; }
        public string Telefone1 { get; set; }
        public string Telefone2 { get; set; }
        public string Contato { get; set; }
        public string InscricaoEstadual { get; set; }
        public string PrioridadeVenda { get; set; }
        public Nullable<System.DateTime> DataCadastro { get; set; }
        public Nullable<System.DateTime> DataAlteracao { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual ICollection<TBT_CARRINHO> TBT_CARRINHO { get; set; }
        public virtual ICollection<TBT_CARTEIRA_CLIENTE> TBT_CARTEIRA_CLIENTE { get; set; }
        public virtual ICollection<TBT_ENDERECO_CLIENTE> TBT_ENDERECO_CLIENTE { get; set; }
        public virtual TBT_GRUPO_CLIENTE TBT_GRUPO_CLIENTE { get; set; }
        public virtual ICollection<TBT_NOTA_FISCAL> TBT_NOTA_FISCAL { get; set; }
        public virtual ICollection<TBT_PEDIDO> TBT_PEDIDO { get; set; }
        public virtual TBT_PESSOA TBT_PESSOA { get; set; }
        public virtual ICollection<TBT_TITULO> TBT_TITULO { get; set; }
        public virtual TBT_SITUACAO_CLIENTE TBT_SITUACAO_CLIENTE { get; set; }
    }
}
