//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_USUARIO
    {
        public TBT_USUARIO()
        {
            this.TBT_CARRINHO = new HashSet<TBT_CARRINHO>();
            this.TBT_PEDIDO = new HashSet<TBT_PEDIDO>();
        }
    
        public decimal CodUsuario { get; set; }
        public string CodPessoa { get; set; }
        public string Login { get; set; }
        public string Senha { get; set; }
        public int IndAtivo { get; set; }
        public string CodMarca { get; set; }
        public string TipoMercado { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual ICollection<TBT_CARRINHO> TBT_CARRINHO { get; set; }
        public virtual ICollection<TBT_PEDIDO> TBT_PEDIDO { get; set; }
        public virtual TBT_PESSOA TBT_PESSOA { get; set; }
    }
}
