//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_MARCA
    {
        public TBT_MARCA()
        {
            this.TBT_CARRINHO = new HashSet<TBT_CARRINHO>();
            this.TBT_LINHA = new HashSet<TBT_LINHA>();
            this.TBT_PEDIDO = new HashSet<TBT_PEDIDO>();
            this.TBT_PESSOA_MARCA = new HashSet<TBT_PESSOA_MARCA>();
        }
    
        public string CodMarca { get; set; }
        public string Descricao { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual ICollection<TBT_CARRINHO> TBT_CARRINHO { get; set; }
        public virtual ICollection<TBT_LINHA> TBT_LINHA { get; set; }
        public virtual ICollection<TBT_PEDIDO> TBT_PEDIDO { get; set; }
        public virtual ICollection<TBT_PESSOA_MARCA> TBT_PESSOA_MARCA { get; set; }
    }
}
