//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_REPRESENTANTE_PREPOSTO
    {
        public string CodPessoaRepresentante { get; set; }
        public string CodPessoaPreposto { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual TBT_PESSOA TBT_PESSOA { get; set; }
        public virtual TBT_PESSOA TBT_PESSOA1 { get; set; }
    }
}
