//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_MODELO
    {
        public TBT_MODELO()
        {
            this.TBT_GRADE_MODELO = new HashSet<TBT_GRADE_MODELO>();
            this.TBT_MARKETING_MODELO = new HashSet<TBT_MARKETING_MODELO>();
            this.TBT_MODELO_TABELA_PRECO = new HashSet<TBT_MODELO_TABELA_PRECO>();
            this.TBT_MODELO_TABELA_PRECO1 = new HashSet<TBT_MODELO_TABELA_PRECO>();
            this.TBT_PRODUTO = new HashSet<TBT_PRODUTO>();
        }
    
        public string CodMarca { get; set; }
        public string CodLinha { get; set; }
        public string CodModelo { get; set; }
        public string Descricao { get; set; }
        public string CodProdutoFoto { get; set; }
        public Nullable<int> Ranking { get; set; }
        public Nullable<int> IndMidia { get; set; }
        public string CodFilial { get; set; }
        public Nullable<System.DateTime> DataVigenciaInicial { get; set; }
        public Nullable<System.DateTime> DataVigenciaFinal { get; set; }
        public Nullable<System.DateTime> DataEntregaInicial { get; set; }
        public Nullable<System.DateTime> DataEntregaFinal { get; set; }
        public string Empresa { get; set; }
        public decimal ID { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
    
        public virtual ICollection<TBT_GRADE_MODELO> TBT_GRADE_MODELO { get; set; }
        public virtual TBT_LINHA TBT_LINHA { get; set; }
        public virtual ICollection<TBT_MARKETING_MODELO> TBT_MARKETING_MODELO { get; set; }
        public virtual ICollection<TBT_MODELO_TABELA_PRECO> TBT_MODELO_TABELA_PRECO { get; set; }
        public virtual ICollection<TBT_MODELO_TABELA_PRECO> TBT_MODELO_TABELA_PRECO1 { get; set; }
        public virtual ICollection<TBT_PRODUTO> TBT_PRODUTO { get; set; }
    }
}
