//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_CRITICA_CARRINHO
    {
        public string CodCarrinho { get; set; }
        public decimal SeqCritica { get; set; }
        public string Critica { get; set; }
        public Nullable<decimal> CodItemCarrinho { get; set; }
        public Nullable<decimal> CodGradeItemCarrinho { get; set; }
        public string CtrlOperacao { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
        public decimal ID { get; set; }
    
        public virtual TBT_CARRINHO TBT_CARRINHO { get; set; }
    }
}
