//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBT_GRADE_ITEM_CARRINHO
    {
        public string CodCarrinho { get; set; }
        public decimal CodItemCarrinho { get; set; }
        public decimal CodGradeItemCarrinho { get; set; }
        public string CodDerivacao { get; set; }
        public decimal Qtd { get; set; }
        public Nullable<decimal> CodInstalacao { get; set; }
        public Nullable<System.DateTime> CtrlDataOperacao { get; set; }
        public decimal ID { get; set; }
    
        public virtual TBT_DERIVACAO TBT_DERIVACAO { get; set; }
        public virtual TBT_ITEM_CARRINHO TBT_ITEM_CARRINHO { get; set; }
    }
}
