//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TMP_FOTO_ARQUIVO
    {
        public string ArquivoFoto { get; set; }
        public string Ano { get; set; }
        public string NomeFotoAjustado { get; set; }
        public string CodModelo { get; set; }
    }
}
